#cloud-config

timezone: Europe/Paris
hostname: coolify

package_update: true
package_upgrade: true

packages:
  - fail2ban
  - rsyslog
  - ufw

ssh_authorized_keys:
%{ for public_key in public_keys ~}
  - ${public_key}
%{ endfor ~}

write_files:
  - content: |
      [sshd]
      enabled  = true
      port     = ${ssh_port}
      filter   = sshd
      maxretry = 3
      findtime = 5m
      bantime  = 30m
    encoding: text/plain
    owner: root:root
    path: /etc/fail2ban/jail.d/sshd.conf
    permissions: "0o644"
  - content: |
      AllowUsers root
      AuthorizedKeysFile .ssh/authorized_keys
      ChallengeResponseAuthentication no
      KbdInteractiveAuthentication no
      MaxAuthTries 3
      PasswordAuthentication no
      PermitRootLogin prohibit-password
      Port ${ssh_port}
      PubkeyAuthentication yes
    encoding: text/plain
    owner: root:root
    path: /etc/ssh/sshd_config.d/cloud-init.conf
    permissions: "0o644"

  # fail2ban for traefik
  - content: |
      [Definition]
      failregex = ^<HOST> -.*"(GET|POST).*HTTP.*" (401|403)
    encoding: text/plain
    owner: root:root
    path: /etc/fail2ban/filter.d/traefik-auth.conf
    permissions: "0o644"
  - content: |
      [Definition]
      failregex = ^<HOST> -.*"(GET|POST).*HTTP.*" 404
    encoding: text/plain
    owner: root:root
    path: /etc/fail2ban/filter.d/traefik-404.conf
    permissions: "0o644"
  - content: |
      [traefik-auth]
      enabled  = true
      port     = 80,443
      filter   = traefik-auth
      logpath  = /data/coolify/proxy/access.log
      maxretry = 5
      findtime = 5m
      bantime  = 30m

      [traefik-404]
      enabled  = true
      port     = 80,443
      filter   = traefik-404
      logpath  = /data/coolify/proxy/access.log
      maxretry = 10
      findtime = 5m
      bantime  = 30m
    encoding: text/plain
    owner: root:root
    path: /etc/fail2ban/jail.d/traefik.conf
    permissions: "0o644"

runcmd:
  - ufw --force reset
  - ufw default deny incoming # block all incoming requests
  - ufw default allow outgoing # allow all outgoing requests

  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw allow 6001/tcp
  - ufw allow 6002/tcp
  - ufw allow 8000/tcp
  - ufw allow ${ssh_port}/tcp

  - ufw --force enable
  - systemctl restart fail2ban ssh

  - env ROOT_USERNAME="${coolify_username}" ROOT_USER_EMAIL="${coolify_email}" ROOT_USER_PASSWORD="${coolify_password}" bash -c 'curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash'
