# Code generated by kickr; DO NOT EDIT.

.PHONY: clean
clean:
	@git clean -dfX

PWD         ?= $(pwd)
TFLINT_PATH ?= .tflint.hcl

.PHONY: lint
lint:
	@tflint --config ${PWD}/${TFLINT_PATH} --recursive --format compact $(ARGS) || \
		echo "tflint failed, running 'make lint-fix' may fix some issues"

.PHONY: lint-fix
lint-fix:
	@ARGS="--fix" make -s lint

plan-modules-github:
	@tofu -chdir=modules/github plan

test-modules-github:
	@tofu -chdir=modules/github test
