# Code generated by kickr; DO NOT EDIT.

.PHONY: clean
clean:
	@git clean -dfX

PWD         ?= $(pwd)
TFLINT_PATH ?= .tflint.hcl

fmt:
	@tofu fmt -diff -recursive

validate:
	@tofu validate

.PHONY: lint
lint:
	@tflint --config "${PWD}/${TFLINT_PATH}" --recursive --format compact $(ARGS) || \
		echo "tflint failed, running 'make lint-fix' may fix some issues"

.PHONY: lint-fix
lint-fix:
	@ARGS="--fix" make -s lint

plan-modules-git:
	@tofu -chdir=modules/git plan

test-modules-git:
	@tofu -chdir=modules/git test

plan-modules-cloud:
	@tofu -chdir=modules/cloud plan

test-modules-cloud:
	@tofu -chdir=modules/cloud test
